### ISSUE TITLE
Install on Openelec: missing cec module

### ISSUE THREAD

**Issue by MrBramme** [michaelarnauts/cec-mqtt-bridge#4]
Hi. 
I'm trying to get this up and running on Openelec. The main issue here is I cannot install packages the normal way.

I've made a minor adjustment in the top lines of the code to allow paho.mqtt to be loaded in there just fine. I've included this at the top:
`import sys
sys.path.append("/storage/scripts/modules")`

and in that folder I've placed the paho.mqtt module. I'm having a problem regarding the cec module though. I can issue commands using command line just fine (example: echo "tx 4F:82:12:00" | cec-client -s ). However, when I start the mqttbrigde it crashes at cec setup:

`Initialising CEC...
('ERROR: Could not initialise CEC:', 'No module named _cec')`

could you help me out? is it possible at all on openelec?

**Comment by michaelarnauts** [comment]
I'm sorry, I don't have an openelec install here. I guess this is related to where packages are installed. 
I'm running this on a rpi with raspbian without issues. I do need to install the packages from the `libcec/` folder however, since the cec-packages from the repository aren't working.
Maybe you can try that? If you still have issues, feel free to reopen.
